### ISSUE TITLE
Prometheus: Exposed Ports

### ISSUE THREAD

**Issue by hwinkel** [rancher/community-catalog#105]
HI,

ist it really required to expose all ports to the hosts?

**Comment by Rucknar** [comment]
The node-exporter - yes. It's recommended to work with host networking, however it seems to work fine in a managed network. This will change with the next update to the catalog entry. 

Ranch-Eye - Not at the moment, it needs to access the local loopback interface, as such it must operate with host networking and with exposed ports.

**Comment by hwinkel** [comment]
hej, thanks for the insides.

**Comment by pierreozoux** [comment]
Do you have an update for this matter?

About Ranch-Eye, can you point to the piece of code that is consuming that endpoint? I'm pretty sure it would be doable to not expose port to the host.

**Comment by Rucknar** [comment]
@pierreozoux [Here](github.com/infinityworksltd/ranch-eye) is the code for this container, it's consumed as an endpoint by prometheus itsself. It requires access to the hosts loopback adaptor (where rancher exposes the cadvisor stats it collects.)

As a result it can't use the managed network or a bridge network without changes to the rancher agent itself. I would much prefer not to listen to a port on the host, however i'm not sure how this would be possible without changing the rancher agent? Happy to accept a pull request though if you can come up with a solution. 

Other ports exposed: 

**Node exporter** - Again due to host networking. You can run node-exporter without host networking (tested), but you lose a good chunk of the networking stats it gathers on the host or it becomes incorrect. 

**Grafana / Prometheus**  Exposed in the catalog so people can get at them, ideally these could be behind a SSL proxy.

**Comment by Rucknar** [comment]
A pull request for the catalog is now in-place. Rancher no longer ships cadvisor by default, the plus side of this is we don't need to map out that port anymore.  @cloudnautique I suspect we can close this one the pull request is merged.

**Comment by Rucknar** [comment]
@cloudnautique Can probably close this one down.
