### ISSUE TITLE
Bug in registry image startup.sh

### ISSUE THREAD

**Issue by AlDemion** [rancher/community-catalog#112]
Hello. There is a bug in https://github.com/sshipway/Portus/blob/master/startup.sh#L40
When you assign IPADDR variable from ip utility output, you need to remove newline between ip's.
Something like:
export IPADDR=`ip addr list eth0 |grep "inet " |cut -d' ' -f6|cut -d/ -f1 | xargs`
@sshipway Please fix it.

**Comment by sshipway** [comment]
@AlDemion  - I've already addressed this in the sshipway/Portus container image here -- basically, I'm removing the ip address part completely as it is not needed.  This just needs to get pushed out to docker hub and we should be OK.   Watch this space...

**Comment by sshipway** [comment]
This seems to affect rancher only, due to the way it has the local docker net and Environment net, resulting in dual IP addresses on eth0.  The solution is, of course, to use `tail -1` to grab the Environment IP address (yes, we could cycle through all of them, but a bit pointless) or to remove the IP altogether as we expose it via the nginx proxy anyway.

I will upload a fix soon.

**Comment by sshipway** [comment]
This is fixed in registry template `2.3.1-3.1` which uses the new `sshipway/portus:2.0.5` container image.

This ticket can be closed.
