### ISSUE TITLE
janitor catalog to enthusiastic in cleaning

### ISSUE THREAD

**Issue by joostliketoast** [rancher/community-catalog#17]
when running the janitor catalog it thought it was a good idea to remove my catalog glusterfs containers and volumes. 

same goes for the gallera db cluster catalog

**Comment by withinboredom** [comment]
+1 ... seems to delete stopped containers even if they are being used.

**Comment by Negashev** [comment]
And MariaDB Galera Cluster

**Comment by sshipway** [comment]
This is correct; the janitor has no way to know if a container was a run-once that needs to be kept, or one that is no longer required.  It only sees a stopped container, orphaned ephemeral filesystem, or unused image. 

What you can do is to exclude the image from the cleanup when you start up Janitor by using the exclude option.  This will mean that it is never cleaned up and so never removed.

Probably, the default exclude option should specify the galera, mariadb and glusterfs images to prevent this.

**Comment by sshipway** [comment]
I have a fix for this: upgrading to the latest docker-cleanup image give a KEEP_CONTAINERS option, and then this needs to be changed to allow wildcards.

There is a pull request in the meltwater queue to add this functionality to the container, and I have an updated template ready to go that uses it (Im trying to avoind having to use my own container image rather than the original).  I'll be submitting a pull req to update the community catalogue item once the container image is updated.

**Comment by hwinkel** [comment]
seems janitor has deleted my rancher-data volume. no mind, was a tests instance anyway. but does janitor volume cleaning as well?

**Comment by sshipway** [comment]
The Janitor template uses the meltwater/docker-cleanup image.  
This removes unused images, stopped containers, and volumes not connected to any container.  Probably, in your case, a stopped run-once sidekick that holds the volume was removed, and this resulted in the volume also being removed?
The latest version of the Template uses a patched version of the container which allows wildcard exclusion of certain images from the cleanup process - so that stopped data-volume containers, and their volumes, will not be removed.  This patch is now accepted into the main meltwater/docker-cleanup project, so a future version of the template will go back to using the official head fork.

**Comment by sshipway** [comment]
Pull req now in place for updated template that uses the latest meltwater image with the regexp filter, with reasonable defaults to disable auto-removing of stopped containers.

This can probably be closed now I think
