### ISSUE TITLE
dnsupdate-rfc2136:AXFR envelope error: dns: no secrets defined

### ISSUE THREAD

**Issue by wangyanbn** [rancher/community-catalog#295]
In Cattle environment, I launched two system stacks: "Bind9 Domain Name Server" and "DNS Update (RFC2136)".
The dns records can be inserted into Bind9.
When the service is failed over to another host, the new ip can be inserted, but the old ip is not removed from the DNS.

There are lots of errors in "DNS Update (RFC2136)" container:
time="2016-09-27T09:22:36Z" level=info msg="DNS records to add: [{memcache.memcache.default.example.com. [100.0.6.152 100.0.6.159] A 59} {bind9.bind9.default.example.com. [100.0.6.152] A 59}]"
time="2016-09-27T09:22:36Z" level=info msg="Adding dns record: {memcache.memcache.default.example.com. [100.0.6.152 100.0.6.159] A 59}"
time="2016-09-27T09:22:37Z" level=error msg="AXFR envelope error: dns: no secrets defined"

Has any one used these templates and can give some help? thanks!

**Comment by rawmind0** [comment]
Hi @wangyanbn ...

what version of dns update (rfc2136) are you using?? 

It seems that TSIG name or key is not correct. I've tried to reporduce your problem, but it seems that works well. Could you please give me more details in order to find out exactly the issue??

Thanks...

**Comment by wbuczak** [comment]
Hello

I've got a similar issue, although I try to configure my rancher's DNS updater (DNS Update (RFC2136) v.0.6.0  so that it updates an external (not hosted on rancher) BIND DNS (v.9).  The external Bind DNS is in the same LAN.  

On the machine where Bind's running, I've generated the TSIG keys with the following:

dnssec-keygen -a HMAC-MD5 -b 128 -n HOST rndc-key

and then I configured them on both sides (the private key is used by my external Bind dns - that's my master if I understand well? ), the public is configured when deploying the DNS Update RFC2136 catalog (that's my slave?) 

Once deployed and started my dnsupdate-rfc2136_rfc2136dns_1 logs following errors:

11/30/2016 10:25:42 AMtime="2016-11-30T09:25:42Z" level=error msg="AXFR envelope error: dns: no secrets defined"

Any hint would be very appreciated! 
Thanks !
Wojtek

**Comment by rawmind0** [comment]
Hi guys,

@wangyanbn ... I've been reading your logs, and it says two thinks... 
- Your connection between bind and external-dns seems to fail in udp 53. Some may errors like that
```
time="2016-11-30T02:26:26Z" level=error msg="Failed to add DNS record to provider {external-dns-adminproject.dayang.com. [bind9.bind9.default.dayang.com.] TXT 30}: RFC2136 query failed: read udp 172.17.0.10:45920->100.0.6.152:53: i/o timeout"
```
- BTW, it seems that bind TSIG keys are not correctly configured. Or may be it's a collateral by the connection problem.
```
time="2016-11-30T02:26:31Z" level=error msg="AXFR envelope error: dns: no secrets defined" 
```
It seems that @wbuczak has the same problem with TSIG keys. 

@wbuczak i think you have to use the key secret on both sides. 

```
dnssec-keygen -a HMAC-SHA1 -b 160 -n HOST rndc-key
```
generates 2 files, *.key and *.private . You need the data named "secret" in *.key or "Key" in *.private 

Just to test and in order to discard bind config problems, could you guys run Bind9 from the catalog and a dnsupdate-rfc2136 connected to it??  It's so quick to do, 5-10 minutes. Once deployed, if it's working ok, you could check and compare bind9 config, yours and the rancher one...

Best regards....

**Comment by wangyanbn** [comment]
@rawmind0 , Thanks a lot!  With your help, I found the cause of this problem and it works now.  
1. The TSIG key name cannot has upper case letters! This seems a bug of DNS Update Service?
When I use "wybTestKey" as name, the DNS Update Service has "AXFR envelope error: dns: no secrets defined" errors, and the old DNS record cannot be deleted, only the new record can be inserted.
But when I dnssec-keygen a new key with "wybtestkey" as name, "AXFR envelope error" disappeared, and old DNS record can also be deleted.

2.  In my test, I always started the bind9 instance from the catalog.  I found using host ip as DNS ip will cause " i/o timeout" error, but the DNS record insert or delete is still OK.
If I use the host ip as DNS IP, the DNS Update Service will has this error:"RFC2136 query failed: read udp 172.17.0.9:60361->100.0.6.152:53: i/o timeout", but the DNS update is success if the key name is in lower case. When I use the bind9.bind9.rancher.internal as DNS IP, there will be no "i/o timeout" error.
We can see the "172.17.0.9" is the DNS Update container ip of docker default network, not of the rancher management network.

**Comment by wbuczak** [comment]
@rawmind0

Thank you very much for your hints.

I finally managed to deploy and configure DNS Update together with Bind 9 DNS on my rancher platform. The updater seems to be correctly putting the DNS records 
of all my services (within my rancher environment) into the DNS. All those, which expose at least one port to the hosting machine.. (which is reasonable, 
though initially I didn't know that and was wondering why the heck it only takes into account a few selected services from my stacks ? :)) 

I'm not entirely sure how this TSIG keys configuration works. I didn't generate the key myself, for now I simply
copy-pasted an example from https://www.cyberciti.biz/faq/unix-linux-bind-named-configuring-tsig/
I did it, as I didn't know how could I generate a key if it is already required by the time one want to deploy  a service ( the DNS or the updater ).  (chicken / egg problem) 
Another question: what is in fact the key name? I took the one from the example mentioned above (secret).
Surpprisingly, it seemed to have worked..

My second task will be to try to configure updater with a DNS working outside the rancher env. We need it because we already have a DNS (bind9) installed in our workplace and
we would like to use that instance (instead of deploying extra DNS for every rancher env).


Once this is done, one remaining issue remains in my case:

We have two networks, let's call it technical (TN) and generic (GN). All hosts configured in Rancher are assigned TN's IP addresses (10.0.3.x) and they can also be accessed from GN
throuhg IP addresses: 192.168.12.X

The DNS updater now takes TN ip addresses and updates DNS with them. I need to alter that behaviour, as the main goal of this whole DNS story in my case is to make possible for some of our 
legacy services (running in GN) to access contenerized services runnig on rancher hosts (no matter on which of the rancher hosts they get deployed)

I guess in order to achive this I'd need to fork and change a bit the Go code of the external-dns ?  So that somehow each time it is about to update the DNS it 
replaces 10.0.3 with 192.168.12 ?

Again, thanks a lot for hints/ideas

**Comment by rawmind0** [comment]
Hi guys,

i'm glad your issues are solved and your systems working right now... :)

@wbuczak ... To expose the services with an ip different that the host is registered in rancher (it seems your need), you could try to use a host label to do it....

```
io.rancher.host.external_dns_ip=<IP_TO_BE_USED_FOR_EXTERNAL_DNS>
```

Look at https://docs.rancher.com/rancher/v1.2/en/cattle/external-dns-service/#using-a-specific-ip-for-external-dns

Best regards....
