### ISSUE TITLE
Catalog Templates and Container Scheduling are Too Tightly Coupled

### ISSUE THREAD

**Issue by mojogitoverhere** [rancher/community-catalog#331]
I think it would be nice to decouple the scheduling of containers with the catalog template. For example, say I want to deploy Elasticsearch 2.X to specific hosts in a production setup because these hosts have more RAM and CPU cores than other nodes in the cluster. As I understand it, I would have to fork this catalog, change the labels on the services and redeploy Elasticsearch 2.X, even though the services themselves did not change at all. If there is an easier way to do it, I am open to suggestions :).

I think this would make the catalog templates a lot more user friendly.

**Comment by rawmind0** [comment]
Hi @mojogitoverhere ..

you are right in this case, but i think that it's not a catalog limitation. 

One of the best practices in this case, would be set host label as a question in rancher-compose.yml , to be able to set it at deployment time.  Then make a PR and it would be useful for all. You could see and example of that at traefik catalog package.
Otherwise, redeployment would be needed if you change host label, due to service would need to be relocated to accomplish the affinity rules.

We are working on decouple best practices in order to avoid this kind of things, and to reuse the most part of code. 

For example, if you build a catalog package to deploy a service in cattle, if you don't take care, probably you need to refactor almost all your code and generate another version to deploy it in kubernetes. We are working in a method, with decoupled pieces, to avoid or minimice that. Kafka and zookeeper catalog packages are an example of that.

If you are interested in the idea and you want to know more, you may take a look at that repo,
https://github.com/rawmind0/docker-alpine

Best regards....

**Comment by rawmind0** [comment]
https://t.co/wAefwuajeQ
