### ISSUE TITLE
Traefik produces stack with no containers

### ISSUE THREAD

**Issue by mikemix** [rancher/community-catalog#718]
Tried to create Traefik stack with no success:

![zaznaczenie_002](https://user-images.githubusercontent.com/2399452/34945878-1a58d470-fa05-11e7-8346-26ab5aa81e5a.png)

Rancher `v1.6.14` on `Docker version 17.12.0-ce, build c97c6d6`

**Comment by lbndev** [comment]
Did you label at least one of your hosts with the "host label" you set when configuring the stack ?
i.e. if "Host label" was "traefik_enabled", then at least one of your environment's host must have a "traefik_enabled=true" label.
Or you can change the scheduling rules for the traefik service so that it deploys on all hosts regardless of the labels.

**Comment by mikemix** [comment]
Wow :) it works! I totally missed that part. Am I supposed to delete rancher's load balancer now since traefik is working?
